### ISSUE TITLE
API access for clock in/out terminal

### ISSUE THREAD

**Issue by niclasku** [bizley/timeclock#17]
Hello,
I would like to add a special API access for a hardware clock in/out terminal and wonder what the right way would look like. My current solution only adds an additional role to the User class and checks for each request if it came from a normal user or the terminal. This is messy because I also have to filter the users based on their roles to let the terminal user not show up anywhere else. 

I think a better solution would consist out of a new API controller class and a terminal class that implements the IdentityInterface. As I have no experience with Yii I would like to ask for your thoughts on this beforehand.

Best regards,
Niclas

**Comment by bizley** [comment]
I'm not sure why does a terminal should act as a user. Perhaps I need more explanations here.

**Comment by niclasku** [comment]
Thanks for your answer!

Users shall use the terminal to clock in/out via RFID tags. The terminal should connect to the timeclock app and do the actual clock in/out. It would be easier to have only one API token for the terminal instead of one token for each user that has to be stored in the terminal. I don't want the terminal to act like users. I was only looking for a way to create a token for the terminal and grant access to a less strict API in order to let the terminal clock in/out every user. 

Additionally my plan was to let admins add a RFID tag ID to each user so that the terminal does not need to store user data.

I hope this explanation was a little clearer.

**Comment by bizley** [comment]
Can you customize the RFIDs with user ID and API key? If so then terminal itself can send requests on behalf of the user.

If not then I would suggest a custom solution like:
- storing RFID tag in user model,
- creating an API endpoint allowing the terminal to send presented tag to the app,
- creating a service that handles the above request and does the clock in/out action using the given RFID tag by finding the user linked with it.

This is a bit more work of course, in addition there would be nice to have admin panel to add/change a user's RFID, and maybe some authentication for terminal API endpoint (like JWT with private/public key).

**Comment by niclasku** [comment]
> If not then I would suggest a custom solution like:
> 
>     * storing RFID tag in user model,
> 
>     * creating an API endpoint allowing the terminal to send presented tag to the app,
> 
>     * creating a service that handles the above request and does the clock in/out action using the given RFID tag by finding the user linked with it.

That's exactly what I want to do :) Regarding authentication: Is it possible to have two classes that implement IdentityInterface so that HttpBearerAuth "asks" both if the Auth Bearer is valid? If not I have to take a look at your suggestion to use JWT.

**Comment by bizley** [comment]
You would have to overwrite the `beforeAction` or `authenticate` method in `HttpBearerAuth` or use your own implementation of IdentityInterface.

**Comment by bizley** [comment]
Hope I helped :) Feel free to ask here if more questions pop up.
