### ISSUE TITLE
New css theme? Can i make a pull request for this?

### ISSUE THREAD

**Issue by HunWalk** [bizley/timeclock#2]
Hi, i've made a css theme for your timeclock, what do you think about it?
Here is some screenshots:
<img width="1432" alt="screenshot 2019-01-18 at 20 58 15" src="https://user-images.githubusercontent.com/32835435/51410132-0240ee00-1b64-11e9-8ed7-4d5e7a60383d.png">
<img width="1430" alt="screenshot 2019-01-18 at 20 58 04" src="https://user-images.githubusercontent.com/32835435/51410138-05d47500-1b64-11e9-9b20-f1a9044fb609.png">

**Comment by HunWalk** [comment]
Also made some hover effects
<img width="1425" alt="screenshot 2019-01-19 at 08 46 58" src="https://user-images.githubusercontent.com/32835435/51423913-f6d2de80-1bc6-11e9-9550-1f8af28252cb.png">

**Comment by bizley** [comment]
[1.6.0](https://github.com/bizley/timeclock/releases/tag/1.6.0) 😄
