### ISSUE TITLE
Autoload.php

### ISSUE THREAD

**Issue by groucha17** [bizley/timeclock#23]
Hi,
I did install your software and as I have tried to point to /public/index.php I had errors I paste  here

Warning: require(/home/clients/ea27f7cbee09d7101a32496af37c62cf/web/pointeuse/public/../vendor/autoload.php): failed to open stream: No such file or directory in /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/pointeuse/public/index.php on line 6

Warning: require(/home/clients/ea27f7cbee09d7101a32496af37c62cf/web/pointeuse/public/../vendor/autoload.php): failed to open stream: No such file or directory in /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/pointeuse/public/index.php on line 6

Fatal error: require(): Failed opening required '/home/clients/ea27f7cbee09d7101a32496af37c62cf/web/pointeuse/public/../vendor/autoload.php' (include_path='.:/opt/php7.3/lib/php') in /home/clients/ea27f7cbee09d7101a32496af37c62cf/web/pointeuse/public/index.php on line 6

The soft does not find the autoload.php. The file seems not to be included in sub folder. Did I miss a step ? What should I do please ?

Regards

Stéphane

**Comment by bizley** [comment]
This info means that something is wrong with composer installation. Composer is creating `autoload.php` file in `vendor` folder. Please check if you have those.
