### ISSUE TITLE
/public/site/login not found

### ISSUE THREAD

**Issue by groucha17** [bizley/timeclock#24]
Hello,
Thank you for the tip about composer. I have followed your installation notes. I have made the configs and everything did well.  I have a new error about the login. The sub folder /public/site/login can not be found. What should I do at this step please ?
Regards,
Stéphane

**Comment by bizley** [comment]
`/site/login` is not a folder, it is a route that should be handled by the `SiteController` (`actionLogin`). If you see this "error" it means that your app is not properly configured. Follow [Configuring Web Servers](https://www.yiiframework.com/doc/guide/2.0/en/start-installation#configuring-web-servers) section of the Yii 2 Guide.

**Comment by groucha17** [comment]
Thanks for the tip. I have updated my .htaccess and everything goes well ! :)
Regards
Stéphane
