### ISSUE TITLE
dwowload csv with the notes included

### ISSUE THREAD

**Issue by groucha17** [bizley/timeclock#25]
Hello,
Really enjoy by your soft, thx ! 
Is there a way to download the csv file with the notes people have written please ?
Regards
Stéphane

**Comment by bizley** [comment]
Yes, it can be added there as well. Would you like to prepare PR for this?

**Comment by groucha17** [comment]
Hello,
Thank you. Well I do not understand what do you mean by PR ? How shall I add the notes to the CSV file please ?
Regards
Stéphane

**Comment by bizley** [comment]
PR stands for [pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests). [This](https://github.com/bizley/timeclock/blob/master/src/controllers/AdminController.php#L317) is the method where CSV data is gathered.

**Comment by groucha17** [comment]
> 
> 
> PR stands for [pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests). [This](https://github.com/bizley/timeclock/blob/master/src/controllers/AdminController.php#L317) is the method where CSV data is gathered.

Hello,
I have created a new menu with Notes in the csv file. I have added it on line 319. I do not know how to call the notes in order they appear when I download it. A bit help is needed please. Sorry I am really bad in php code ;) Finally I will do a PR to the other users.
Regards
Stéphane

**Comment by bizley** [comment]
Something like

```
        $content = [['Name', 'Date', 'Project', 'In', 'Out', 'Time', 'Note']];

        /* @var $session Clock */
        foreach ($sessions as $session) {
            $content[] = [
                $users[$session->user_id]->name,
                Yii::$app->formatter->asDate($session->clock_in, 'yyyy-MM-dd'),
                $session->project_id ? $session->project->name : '',
                Yii::$app->formatter->asTime($session->clock_in, 'HH:mm'),
                $session->clock_out ? Yii::$app->formatter->asTime($session->clock_out, 'HH:mm') : '???',
                $session->clock_out ? round(($session->clock_out - $session->clock_in) / 3600, 2) : '???',
                $session->note
            ];
        }
```

should be enough.

**Comment by groucha17** [comment]
It works, thank you :)
