### ISSUE TITLE
Cannot create a project with assigned users

### ISSUE THREAD

**Issue by husim0** [bizley/timeclock#46]
Hello,

Thank you for your software, it is really useful.

I have a trouble creating a project with assigned users.

I have the following error :  
```
SQLSTATE[23000]: Integrity constraint violation: 4025 CONSTRAINT `project.assignees` failed for `timeclock`.`project`
The SQL being executed was: INSERT INTO `project` (`name`, `color`, `assignees`, `created_at`, `updated_at`) VALUES ('test', '#60a193', 'Array', 1652104178, 1652104178)

Error Info: Array
(
    [0] => 23000
    [1] => 4025
    [2] => CONSTRAINT `project.assignees` failed for `timeclock`.`project`
)

↵
Caused by: PDOException
SQLSTATE[23000]: Integrity constraint violation: 4025 CONSTRAINT `project.assignees` failed for `timeclock`.`project`
```

Please tell me if I can give you any other information.

Have a nice day, thank you

**Comment by husim0** [comment]
Hello, thank you for your reply. I'm using mariadb 10.7, so something pretty common I guess.

**Comment by bizley** [comment]
See https://github.com/SAM-IT/yii2-mariadb

**Comment by husim0** [comment]
Ok, so what should I do, sorry I'm not familiar at all with Yii Framework. Do I need to use that dependency and then follow what is described in the README ?

**Comment by bizley** [comment]
Well, yes.

**Comment by Dedofugaz** [comment]
I'm sorry, I tried my best at implementing what you are saying but I really don't understand where to apply this solution.
I know it's really too much to ask but did any of you really accomplish adding users to a project with mariadb? if so... could you guide me just a little?
The app is wonderful and right now the test users only can register at ongoing...
Thanks and if this is not correct feel free to delete this comment...
